tasks/urls.py
from django.urls import path

from tasks import views


app_name = "tasks"

urlpatterns = [
    # tasks
    path("", views.TaskListView.as_view(), name="task-list"),
    path("create/", views.TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/update/", views.TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>delete/", views.TaskDeleteView.as_view(), name="task-delete"),
    path("<int:pk>/toggle/", views.task_toggle_completion, name="task-toggle-completion"),

    # tags
    path("tags/", views.TagListView.as_view(), name="tag-list"),
    path("tags/create/", views.TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", views.TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>delete/", views.TagDeleteView.as_view(), name="tag-delete"),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tasks.urls", namespace="tasks")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name


class Task(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, blank=True, related_name="tasks")

    class Meta:
        ordering = ("is_done", "-created")

    def __str__(self):
        return self.title



tasks/forms.py
from django import forms

from tasks.models import Tag, Task


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        required=False,
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )
    deadline = forms.DateTimeField(
        required=False,
        widget=forms.DateTimeInput(
            attrs={
                "type": 'datetime-local',
            }
        )
    )

    class Meta:
        model = Task
        fields = ("title", "content", "deadline", "tags")

tasks/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic

from tasks.forms import TaskForm
from tasks.models import Tag, Task


class TagListView(generic.ListView):
    model = Tag
    context_object_name = "tags"


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("tasks:tag-list")


class TaskListView(generic.ListView):
    model = Task
    context_object_name = "tasks"


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("tasks:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("tasks:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("tasks:task-list")


def task_toggle_completion(request, pk):
    if request.method == "POST":
        task = Task.objects.get(pk=pk)
        task.is_done = not task.is_done
        task.save()
    return redirect("tasks:task-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Taxi Service</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group card">
  <li class="list-group-item"><a href="{% url 'tasks:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'tasks:tag-list' %}">Tags</a></li>
</ul>

templates/tasks/tag_confirm_delete.html
{% extends "base.html" %}

{% block title %}<title>Delete tag</title>{% endblock %}

{% block content %}
  <h1>Delete "{{ tag.name }}" tag?</h1>
  <form action="" method="post">
  {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Yes">
  </form>
{% endblock %}

templates/tasks/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}<title>{{ object|yesno:"Update,Create" }} tag</title>{% endblock %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <div class="card">
    <div class="card-body">
      <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}

        <input class="btn btn-primary" type="submit" value="Submit">
      </form>
    </div>
  </div>
{% endblock %}

templates/tasks/tag_list.html
{% extends "base.html" %}

{% block title %}<title>Tags</title>{% endblock %}

{% block content %}
  <div class="d-flex justify-content-between">
    <h1>Tags</h1>
    <div>
      <a class="btn btn-primary" href="{% url 'tasks:tag-create' %}">Add tag</a>
    </div>
  </div>
  <hr>
  {% if tags %}
    <table class="table table-striped">
    
      <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
      </tr>
      </thead>
    
      <tbody>
      {% for tag in tags %}
        <tr>
          <td>{{ tag.name }}</td>
          <td><a class="btn btn-secondary" href="{% url 'tasks:tag-update' pk=tag.pk %}">Update</a></td>
          <td><a class="btn btn-secondary" href="{% url 'tasks:tag-delete' pk=tag.pk %}">Delete</a></td>
        </tr>
      {% endfor %}
      </tbody>
    
    </table>
  {% else %}
    <p>No tags yet.</p>
  {% endif %}
{% endblock %}

templates/tasks/task_confirm_delete.html
{% extends "base.html" %}

{% block title %}<title>Delete task</title>{% endblock %}

{% block content %}
  <h1>Delete "{{ task.title }}" task?</h1>
  <form action="" method="post">
  {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Yes">
  </form>
{% endblock %}

templates/tasks/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}<title>{{ object|yesno:"Update,Create" }} task</title>{% endblock %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <div class="card">
    <div class="card-body">
      <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}

        <input class="btn btn-primary" type="submit" value="Submit">
      </form>
    </div>
  </div>
{% endblock %}

templates/tasks/task_list.html
{% extends "base.html" %}

{% block title %}<title>TODO</title>{% endblock %}

{% block content %}
  <div class="d-flex justify-content-between">
    <h1>TODO list</h1>
    <div>
      <a class="btn btn-primary" href="{% url 'tasks:task-create' %}">Add task</a>
    </div>
  </div>
  {% if tasks %}
    {% for task in tasks %}

      <div class="card mb-3">
       
        <div class="card-body">
          <div class="d-flex justify-content-between">
            <div class="card-title">
              <h5 class="d-inline">{{ task.title }}</h5>
              {% if task.is_done %}
                <h5 class="text-success d-inline">Done</h5>
              {% else %}
                <h5 class="text-danger d-inline">Not done</h5>
              {% endif %}
            </div>
            <form action="{% url 'tasks:task-toggle-completion' pk=task.pk %}" method="post">
              {% csrf_token %}
              {% if task.is_done %}
                <input class="btn btn-secondary" type="submit" value="Undo">
                {% else %}
                <input class="btn btn-success" type="submit" value="Complete">
              {% endif %} 
            </form>
          </div>
          {% if task.tags.all %}
            <h6 class="card-subtitle mb-2 text-body-secondary">
              Tags:
              {% for tag in task.tags.all %}
                {{ tag.name }}
              {% endfor %}
            </h6>
          {% endif %}
          
        {% if task.content %}
          <p class="card-text">{{ task.content }}</p>
        {% endif %}
          <a href="{% url 'tasks:task-update' pk=task.pk %}">Update</a>
          <a href="{% url 'tasks:task-delete' pk=task.pk %}">Delete</a>
        </div>

        <div class="card-footer">
          <p class="card-text">
            <small class="text-body-secondary">Created: {{ task.created }}</small>
            {% if task.deadline %}
              <small class="text-danger ">Deadline: {{ task.deadline }}</small>
            {% endif %}
          </p>
        </div>
      
      </div>

    {% endfor %}
  {% else %}
    <p>No tasks yet.</p>
  {% endif %}
{% endblock %}